review_version: 5.9

bookname: iOSDC-Japan-2024-Manuscript
language: ja
booktitle: {name: "SwiftLintのオレオレカスタムルール一覧", file-as: "swiftlintノオレオレカスタムルールイチラン"}
aut: [{name: "ウホーイ", file-as: "ウホーイ"}]
edt: ["ウホーイ"]
pbl: The Uhooi
date: 2024-08-22
history: [["2024-08-22 iOSDC Japan 2024版 v1.0.0"]]
rights: (C) 2024 The Uhooi
debug: true
urnid: urn:uuid:https://github.com/uhooi/iOSDC2020-GitHubActions-Manuscript
htmlext: html
stylesheet: ["style.css"]
epubversion: 3
htmlversion: 5
toclevel: 3
secnolevel: 3
toc: false
titlepage: false
colophon: false
highlight:
  latex: "listings"
table_row_separator: verticalbar
direction: "ltr"

playwright_options:
  playwright_path: "/usr/bin/playwright"

epubmaker:
  htmlext: xhtml
  stylesheet: ["style.css", "epub_style.css"]

texstyle: ["reviewmacro"]

# A4の設定(9pt 53文字×50行) - 紙版
# texdocumentclass: ["review-jsbook", "media=print,paper=a4,serial_pagination=true,hiddenfolio=nikko-pc,openany,fontsize=9pt,baselineskip=14pt,line_length=53zw,number_of_lines=50,head_space=15mm,headsep=3mm,headheight=5mm,footskip=10mm,gutter=25mm"]
# A4の設定(10pt 48文字×44行) - 紙版
texdocumentclass: ["review-jsbook", "media=print,paper=a4,serial_pagination=true,hiddenfolio=nikko-pc,openany,fontsize=10pt,baselineskip=16pt,line_length=48zw,number_of_lines=44,head_space=15mm,headsep=3mm,headheight=5mm,footskip=10mm,gutter=25mm"]

pdfmaker:
  colophon: false

webmaker:
    stylesheet: ["style.css", "style-web.css"]
